[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/**"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://region2.google-analytics.com https://www.googletagmanager.com; img-src 'self' data: https://www.google-analytics.com https://stats.g.doubleclick.net; style-src 'self' 'unsafe-inline'; frame-src https://www.googletagmanager.com;"



