[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/**"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://region2.google-analytics.com https://www.googletagmanager.com; img-src 'self' data: https://www.google-analytics.com https://stats.g.doubleclick.net https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; frame-src https://www.googletagmanager.com;"

[[headers]]
  for = "/sitemap-index.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=600"

[[headers]]
  for = "/sitemap-*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap-index.xml"
  status = 301



